Repository project-codeblue/CodeBlue, pull requests merged in 2023-06, with the labels that each got.

#59 test: e2e test 1차 완료
  config/db.config.ts
  src/app.module.ts
  src/commons/providers/typeorm-config.provider.ts
  src/hospitals/hospitals.module.ts
  src/requests/service/requests.service.ts
  test/app.e2e-spec.ts
Labels: test, help wanted

#63 !BREAKING CHANGE: hospitals 엔티티 변경 및 spatial Index 수정
  src/hospitals/hospitals.entity.ts
  src/hospitals/hospitals.repository.ts
  src/hospitals/service/hospitals.service.ts
Labels: bug, help wanted

#65 fix: hospitals Spatial Index 적용에 따른 repository 쿼리 변경
  src/hospitals/hospitals.repository.ts
  src/reports/reports.repository.ts
  src/requests/service/requests.service.ts
Labels: bug

#66 feat: 환자 정보 입력 API 완료
  src/commons/providers/typeorm-config.provider.ts
  src/hospitals/hospitals.repository.ts
  src/patients/controller/patients.controller.spec.ts
  src/patients/controller/patients.controller.ts
  src/patients/dto/create-patient.dto.ts
  src/patients/patients.module.ts
  src/patients/patients.repository.ts
  src/patients/pipe/gender-from-rrn.pipe.ts
  src/patients/service/patients.service.spec.ts
  src/patients/service/patients.service.ts
  src/reports/controller/reports.controller.ts
  src/reports/dto/update-report.dto.ts
  src/reports/reports.repository.ts
  src/reports/service/reports.service.ts
  src/requests/service/requests.service.ts
Labels: bug

#72 test: 증상 보고서 수정, 환자 정보 입력, 이송 신청, 이송 신청 철회 API unit test 완료
  package.json
  src/commons/utils/html-jest-report/jest-html-reporters-attach/report/result.js
  src/patients/controller/patients.controller.spec.ts
  src/patients/dto/create-patient.dto.ts
  src/patients/patients.module.ts
  src/patients/service/patients.service.spec.ts
  src/patients/service/patients.service.ts
  src/reports/controller/reports.controller.spec.ts
  src/reports/controller/reports.controller.ts
  src/reports/reports.entity.ts
  src/reports/reports.module.ts
  src/reports/reports.repository.ts
  src/reports/service/reports.service.spec.ts
  src/reports/service/reports.service.ts
  src/requests/controller/requests.controller.spec.ts
  src/requests/controller/requests.controller.ts
  src/requests/service/requests.service.spec.ts
  src/requests/service/requests.service.ts
  test/app.e2e-spec.ts
Labels: test

#73 test: e2e test 2차 완료
  src/hospitals/service/hospitals.service.ts
  src/patients/service/patients.service.ts
  src/reports/reports.repository.ts
  src/reports/service/reports.service.ts
  src/requests/service/requests.service.ts
  test/app.e2e-spec.ts
Labels: bug, test, yougotmelookingforattention~

#76 feat: patient table 생성을 위한 증상보고서 api 수정 + 증상보고서 상세조회 수정 완료
  src/patients/controller/patients.controller.ts
  src/patients/patients.repository.ts
  src/reports/constants/symptoms.ts
  src/reports/controller/reports.controller.ts
  src/reports/dto/create-report.dto.ts
  src/reports/dto/update-report.dto.ts
  src/reports/reports.repository.ts
  src/reports/service/reports.service.ts
Labels: yougotmelookingforattention~, question

#78 feat: 환자 정보 수정 API 완료 & 단위 테스트
  src/commons/utils/html-jest-report/jest-html-reporters-attach/report/result.js
  src/hospitals/hospitals.repository.ts
  src/patients/controller/patients.controller.spec.ts
  src/patients/controller/patients.controller.ts
  src/patients/dto/update-patient.dto.ts
  src/patients/patients.repository.ts
  src/patients/service/patients.service.spec.ts
  src/patients/service/patients.service.ts
  src/reports/service/reports.service.spec.ts
  src/requests/service/requests.service.spec.ts
  src/requests/service/requests.service.ts
Labels: bug, test

#80 fix: 증상 보고서 상세 조회 repository 분기 처리 & e2e test 마무리
  src/commons/utils/html-jest-report/jest-html-reporters-attach/report/result.js
  src/patients/controller/patients.controller.ts
  src/patients/patients.repository.ts
  src/patients/pipe/gender-from-rrn.pipe.ts
  src/patients/service/patients.service.ts
  src/reports/reports.repository.ts
  src/reports/service/reports.service.ts
  test/app.e2e-spec.ts
Labels: bug, test

#81 fix: patients service unit test 사소한 수정
  src/commons/utils/html-jest-report/jest-html-reporters-attach/report/result.js
  src/patients/service/patients.service.spec.ts
Labels: test

#82 refactor: 증상 보고서 상세 조회 repository -> service로 비지니스 로직 이동
  src/commons/utils/html-jest-report/jest-html-reporters-attach/report/result.js
  src/reports/reports.repository.ts
  src/reports/service/reports.service.spec.ts
  src/reports/service/reports.service.ts
Labels: test, refactoring

#86 feat: 동시성 제어 bullqueue 추가
  docker-compose.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/commons/providers/typeorm-config.provider.ts
  src/commons/utils/html-jest-report/jest-html-reporters-attach/report/result.js
  src/hospitals/hospitals.repository.ts
  src/hospitals/service/hospitals.service.ts
  src/main.ts
  src/reports/reports.enum.ts
  src/reports/reports.repository.ts
  src/reports/service/reports.service.spec.ts
  src/reports/service/reports.service.ts
  src/requests/controller/requests.controller.ts
  src/requests/requests.consumer.ts
  src/requests/requests.module.ts
  src/requests/service/requests.service.spec.ts
  src/requests/service/requests.service.ts
  test/artillery/concurrency.test.script.yaml
  test/artillery/data.csv
  test/artillery/html-artillery-report.json
  test/artillery/html-artillery-report.json.html
  test/html-jest-report/jest-html-reporters-attach/report/index.js
  test/html-jest-report/jest-html-reporters-attach/report/result.js
  test/html-jest-report/report.html
Labels: bug, enhancement

#87 feat: 추천 병원 조회 API redis 캐싱 적용
  package-lock.json
  package.json
  src/hospitals/hospitals.entity.ts
  src/hospitals/hospitals.module.ts
  src/hospitals/service/hospitals.service.ts
  src/requests/requests.module.ts
  test/artillery/concurrency.test.script.yaml
  test/supertest-e2e/app.e2e-spec.ts
  test/supertest-e2e/jest-e2e.json
Labels: enhancement

#88 fix: 병원 조회 API caching radius & max_count 변경시 새로운 caching 만들기
  src/hospitals/service/hospitals.service.ts
  src/reports/service/reports.service.ts
Labels: bug

#89 feat: 검색 기능 개선 및 취약점 보완
  config/app.config.ts
  config/db.config.ts
  package-lock.json
  package.json
  src/commons/middlewares/crawling.ts
  src/commons/middlewares/elk.ts
  src/hospitals/controller/hospitals.controller.ts
  src/hospitals/service/hospitals.service.ts
  src/requests/controller/requests.controller.spec.ts
  src/requests/controller/requests.controller.ts
  src/requests/requests.module.ts
  src/requests/service/requests.service.spec.ts
  src/requests/service/requests.service.ts
  test/artillery/concurrency.test.script.yaml
  test/artillery/hospital-recommend.yaml
  test/artillery/patient-update.yaml
  test/artillery/report-detail.yaml
  test/artillery/report-search.yaml
  test/artillery/report-update.yaml
  test/artillery/withdraw-request.yaml
Labels: bug, enhancement, refactoring

#108 feat: Docker & Nginx 설정 및 검색 쿼리 수정
  docker-compose.yml
  package-lock.json
  package.json
  proxy/nginx.conf
  src/commons/middlewares/elk.ts
  src/reports/controller/reports.controller.ts
  src/reports/reports.repository.ts
  src/reports/service/reports.service.ts
  src/requests/controller/requests.controller.ts
  src/requests/requests.module.ts
  src/requests/service/requests.service.ts
Labels: bug, refactoring

#109 fix: 검색 FE 날짜 당일까지만 선택할 수 있게 max_date 설정 & 증상명으로 검색 추가
  views/reportSearchEngine.ejs
Labels: bug

#112 feat: 분산 서버 구축을 위한 환경 설정과 Redis 오류 수정 및 FE 작업
  docker-compose.yml
  package-lock.json
  package.json
  proxy/nginx.conf
  public/image/codeblue-favicon.png
  src/app.controller.ts
  src/hospitals/hospitals.module.ts
  src/reports/service/reports.service.ts
  views/index.ejs
  views/recommendedHospitals.ejs
  views/reportDetail.ejs
  views/reportSearchEngine.ejs
  views/searchResult.ejs
Labels: bug, enhancement, refactoring

#113 fix: querySelector 버그 수정
  views/createReport.ejs
Labels: bug

#120 fix: 동시성 제어 Redis 에러 수정 및 부하 테스트 작성
  config/app.config.ts
  docker-compose.yml
  src/hospitals/hospitals.module.ts
  src/main.ts
  src/requests/controller/requests.controller.ts
  src/requests/requests.module.ts
  src/requests/service/requests.service.ts
  test/artillery/access-mainpage.yaml
  test/artillery/hospital-recommend-repeat.csv
  test/artillery/hospital-recommend-repeat.yaml
  test/artillery/hospital-recommend.yaml
  test/artillery/patient-request-01.csv
  test/artillery/patient-request-02.csv
  test/artillery/patient-request-03.csv
  test/artillery/patient-request.csv
  test/artillery/patient-request.yaml
  test/artillery/patient-request4.csv
  test/artillery/report-detail.yaml
  test/artillery/report-search.yaml
  test/artillery/report/access-mainpage_ec2_60_100.html
  test/artillery/report/access-mainpage_ec2_60_100.json
  test/artillery/report/access-mainpage_ec2_60_30.html
  test/artillery/report/access-mainpage_ec2_60_30.json
  test/artillery/report/access-mainpage_ec2_60_500.html
  test/artillery/report/access-mainpage_ec2_60_500.json
  test/artillery/report/access-mainpage_ec2x3_60_100.html
  test/artillery/report/access-mainpage_ec2x3_60_100.json
  test/artillery/report/access-mainpage_ec2x3_60_30.html
  test/artillery/report/access-mainpage_ec2x3_60_30.json
  test/artillery/report/access-mainpage_ec2x3_60_500.html
  test/artillery/report/access-mainpage_ec2x3_60_500.json
  test/artillery/report/html-artillery-report.html
  test/artillery/report/html-artillery-report.json
  test/artillery/report/patient-request.json
  test/artillery/report/report-search_ec2_60_100.html
  test/artillery/report/report-search_ec2_60_100.json
  test/artillery/report/report-search_ec2_60_30.html
  test/artillery/report/report-search_ec2_60_30.json
  test/artillery/report/report-search_ec2_60_500.html
  test/artillery/report/report-search_ec2_60_500.json
  test/artillery/report/report-search_ec2x3_60_100.html
  test/artillery/report/report-search_ec2x3_60_100.json
  test/artillery/report/report-search_ec2x3_60_30.html
  test/artillery/report/report-search_ec2x3_60_30.json
  test/artillery/report/report-search_ec2x3_60_500.html
  test/artillery/report/report-search_ec2x3_60_500.json
  views/createReport.ejs
  views/index.ejs
  views/recommendedHospitals.ejs
  views/reportDetail.ejs
  views/reportSearchEngine.ejs
  views/searchResult.ejs
Labels: bug, test, refactoring

#123 feat: redis cloud 연결
  config/app.config.ts
  config/redis.config.ts
  src/hospitals/hospitals.module.ts
  src/reports/service/reports.service.ts
  src/requests/requests.module.ts
  views/recommendedHospitals.ejs
Labels: bug

#129 refactor: redis 캐싱 service layer -> cache interceptor
  config/redis.config.ts
  src/commons/interceptors/cache.interceptor.ts
  src/commons/providers/bull-config.provider.ts
  src/commons/providers/kakao-map.provider.ts
  src/commons/providers/redis-config.provider.ts
  src/commons/providers/typeorm-config.provider.ts
  src/hospitals/controller/hospitals.controller.ts
  src/hospitals/hospitals.module.ts
  src/hospitals/service/hospitals.service.spec.ts
  src/hospitals/service/hospitals.service.ts
  src/reports/reports.module.ts
  src/requests/requests.consumer.ts
  src/requests/requests.module.ts
  src/requests/service/requests.service.ts
  test/artillery/concurrency.test.script.yaml
Labels: refactoring

#130 fix: max_count & radius 반영시 새로고침 버그 수정
  src/commons/interceptors/cache.interceptor.ts
  src/commons/providers/redis-config.provider.ts
  src/hospitals/hospitals.module.ts
  views/createReport.ejs
  views/recommendedHospitals.ejs
Labels: bug

#131 fix: 이송신청, 철회시 관련 cached data 삭제
  src/commons/interceptors/cache.interceptor.ts
  src/commons/interceptors/clear-cache.interceptor.ts
  src/hospitals/controller/hospitals.controller.ts
  src/hospitals/service/hospitals.service.ts
  src/requests/controller/requests.controller.ts
  src/requests/requests.module.ts
  test/artillery/concurrency.test.script.yaml
  views/createReport.ejs
  views/recommendedHospitals.ejs
Labels: bug, refactoring

#134 fix: 동시성 제어 오류 및 부하 테스트 수정
  src/commons/providers/bull-config.provider.ts
  src/commons/providers/redis-config.provider.ts
  src/requests/controller/requests.controller.ts
  src/requests/requests.consumer.ts
  src/requests/service/requests.service.ts
  test/artillery/concurrency.test.script.csv
  test/artillery/patient-request-01.csv
  test/artillery/patient-request-02.csv
  test/artillery/patient-request-03.csv
  test/artillery/patient-request.yaml
  test/artillery/patient-request2.yaml
  test/artillery/report/patient-request.json
  test/artillery/report/patient-request2.json
  views/recommendedHospitals.ejs
  views/reportSearchEngine.ejs
Labels: bug, test, refactoring

#135 fix: FE 이송신청 & 철회시 cache 지워지고 새로고침
  src/requests/service/requests.service.ts
  views/recommendedHospitals.ejs
Labels: bug

#137 fix: FE 증상보고서 상세조회 & 검색 결과 버그 수정
  src/app.controller.ts
  src/reports/reports.repository.ts
  views/createReport.ejs
  views/index.ejs
  views/nearbyHospitals.ejs
  views/recommendedHospitals.ejs
  views/reportDetail.ejs
  views/reportSearchEngine.ejs
  views/searchResult.ejs
Labels: bug, refactoring

#139 fix: 동시성 제어를 위한 코드 설정 및 기타 에러 수정
  src/app.controller.ts
  src/hospitals/controller/hospitals.controller.ts
  src/reports/controller/reports.controller.ts
  src/reports/service/reports.service.ts
  src/requests/controller/requests.controller.ts
  src/requests/requests.consumer.ts
  src/requests/service/requests.service.ts
  test/artillery/patient-request.yaml
  test/artillery/report/patient-request.json
  views/createReport.ejs
  views/nearbyHospitals.ejs
  views/recommendedHospitals.ejs
  views/reportDetail.ejs
  views/reportSearchEngine.ejs
  views/searchResult.ejs
Labels: bug, test, refactoring

#140 fix: FE 페이지 로딩시 로딩 이미지 띄우기
  views/createReport.ejs
  views/nearbyHospitals.ejs
  views/recommendedHospitals.ejs
  views/reportDetail.ejs
  views/reportSearchEngine.ejs
  views/searchResult.ejs
Labels: refactoring

#143 style: FE index 페이지 변경 & 입력 페이지 가운데 정렬 조정
  public/image/gif.gif
  src/app.controller.ts
  src/reports/service/reports.service.ts
  src/requests/requests.consumer.ts
  views/createReport.ejs
  views/index.ejs
  views/nearbyHospitals.ejs
  views/recommendedHospitals.ejs
  views/reportSearchEngine.ejs
  views/searchResult.ejs
Labels: bug, refactoring

#145 fix: 가까운 병원 조회 에러 수정, 화면 단 레이아웃 조정 및 부하 테스트 마무리
  test/artillery/hospital-recommend-repeat.yaml
  test/artillery/patient-request-00.csv
  test/artillery/patient-request-01.csv
  test/artillery/patient-request.csv
  test/artillery/patient-request.yaml
  test/artillery/patient-request2.yaml
  test/artillery/patient-request4.csv
  test/artillery/report/hospital-recommend-repeat_ec2_60_10.html
  test/artillery/report/hospital-recommend-repeat_ec2_60_10.json
  test/artillery/report/hospital-recommend-repeat_ec2_60_100.html
  test/artillery/report/hospital-recommend-repeat_ec2_60_100.json
  test/artillery/report/hospital-recommend-repeat_ec2_60_20.html
  test/artillery/report/hospital-recommend-repeat_ec2_60_20.json
  test/artillery/report/hospital-recommend-repeat_ec2_60_50.html
  test/artillery/report/hospital-recommend-repeat_ec2_60_50.json
  test/artillery/report/hospital-recommend-repeat_ec2x3_60_10.html
  test/artillery/report/hospital-recommend-repeat_ec2x3_60_10.json
  test/artillery/report/hospital-recommend-repeat_ec2x3_60_100.html
  test/artillery/report/hospital-recommend-repeat_ec2x3_60_100.json
  test/artillery/report/hospital-recommend-repeat_ec2x3_60_20.html
  test/artillery/report/hospital-recommend-repeat_ec2x3_60_20.json
  test/artillery/report/hospital-recommend-repeat_ec2x3_60_50.html
  test/artillery/report/hospital-recommend-repeat_ec2x3_60_50.json
  test/artillery/report/patient-request.json
  views/createReport.ejs
  views/recommendedHospitals.ejs
  views/reportSearchEngine.ejs
Labels: bug, test, refactoring

#155 style: FE footer 수정 & 위치 재반영 버튼
  src/patients/pipe/patient-body-data-validation.pipe.ts
  views/createReport.ejs
  views/nearbyHospitals.ejs
  views/recommendedHospitals.ejs
  views/reportDetail.ejs
  views/reportSearchEngine.ejs
  views/searchResult.ejs
Labels: bug

#158 fix: 증상보고서 입력시 이름 필드 추가
  src/reports/controller/reports.controller.ts
  src/reports/dto/create-report.dto.ts
  src/reports/service/reports.service.ts
  views/createReport.ejs
Labels: bug

#161 fix: FE navbar 모바일 햄버거 수정
  src/hospitals/service/hospitals.service.ts
  src/reports/dto/create-report.dto.ts
  views/createReport.ejs
  views/nearbyHospitals.ejs
  views/recommendedHospitals.ejs
  views/reportDetail.ejs
  views/reportSearchEngine.ejs
  views/searchResult.ejs
Labels: bug

#163 fix: 병원 조회시 카카오 모빌리티 API 거리 측정과 MySQL spatial index의 거리 측정 오차 이슈
  src/hospitals/service/hospitals.service.ts
  views/recommendedHospitals.ejs
Labels: bug

#164 fix: Redis 이중화를 위한 Bull Queue Config 수정 및 가까운 병원 코드 수정
  src/commons/providers/bull-config.provider.ts
  views/nearbyHospitals.ejs
Labels: enhancement

#165 refactor: transaction 및 기타 코드 리팩토링
  package-lock.json
  package.json
  src/app.module.ts
  src/hospitals/service/hospitals.service.ts
  src/patients/service/patients.service.ts
  src/reports/controller/reports.controller.ts
  src/reports/service/dataset_fifth.ts
  src/reports/service/reports.service.ts
  src/requests/service/requests.service.ts
Labels: refactoring

#166 refactor: 크롤링 리팩토링 및 메디서비스 API 제거
  config/app.config.ts
  src/commons/middlewares/crawling.ts
  src/commons/middlewares/medicalOpenAPI.ts
  src/hospitals/hospitals.module.ts
  src/hospitals/service/hospitals.service.ts
Labels: refactoring

#169 fix: FE 에러 메세지 반환 수정 & 검색 엔진 초기화 버튼
  src/commons/middlewares/crawling.ts
  src/hospitals/controller/hospitals.controller.ts
  src/hospitals/service/hospitals.service.spec.ts
  src/hospitals/service/hospitals.service.ts
  src/reports/service/reports.service.spec.ts
  src/reports/service/reports.service.ts
  src/requests/controller/requests.controller.ts
  test/html-jest-report/jest-html-reporters-attach/report/result.js
  views/recommendedHospitals.ejs
  views/reportSearchEngine.ejs
  views/searchResult.ejs
Labels: bug

#171 fix: FE 병원조회 & 근처 병원 조회 페이지 버그 수정
  src/hospitals/service/hospitals.service.ts
  views/nearbyHospitals.ejs
  views/recommendedHospitals.ejs
Labels: bug

#176 refactor: 메서드 타입 지정 및 주석 달기
  src/app.module.ts
  src/app.service.ts
  src/hospitals/controller/hospitals.controller.ts
  src/hospitals/hospitals.repository.ts
  src/hospitals/service/hospitals.service.spec.ts
  src/hospitals/service/hospitals.service.ts
  src/patients/controller/patients.controller.ts
  src/patients/patients.repository.ts
  src/patients/service/patients.service.ts
  src/reports/controller/reports.controller.ts
  src/reports/reports.repository.ts
  src/reports/service/dataset_fifth.ts
  src/reports/service/patient-update.txt
  src/reports/service/reports.service.ts
  src/requests/controller/requests.controller.ts
  src/requests/requests.consumer.ts
  src/requests/requests.module.ts
  src/requests/service/requests.service.ts
Labels: refactoring
